// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOGjQpg92CSWY8j_MMve4JXxfs4mk5lc',
    appId: '1:720438105685:web:1aa11b0aabec0afc1a26dc',
    messagingSenderId: '720438105685',
    projectId: 'smart-ats-qr-code',
    authDomain: 'smart-ats-qr-code.firebaseapp.com',
    storageBucket: 'smart-ats-qr-code.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA52ZoAPFIQ6xvPqu4GZ8njA4GwExjYOCM',
    appId: '1:720438105685:android:68a37d9c9e8228bc1a26dc',
    messagingSenderId: '720438105685',
    projectId: 'smart-ats-qr-code',
    storageBucket: 'smart-ats-qr-code.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOO_i7bR7KUW3MK-QXf2xlT8zcd0tbvH8',
    appId: '1:720438105685:ios:914b766500bdb4b01a26dc',
    messagingSenderId: '720438105685',
    projectId: 'smart-ats-qr-code',
    storageBucket: 'smart-ats-qr-code.firebasestorage.app',
    iosBundleId: 'com.example.smartAts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOO_i7bR7KUW3MK-QXf2xlT8zcd0tbvH8',
    appId: '1:720438105685:ios:914b766500bdb4b01a26dc',
    messagingSenderId: '720438105685',
    projectId: 'smart-ats-qr-code',
    storageBucket: 'smart-ats-qr-code.firebasestorage.app',
    iosBundleId: 'com.example.smartAts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEOGjQpg92CSWY8j_MMve4JXxfs4mk5lc',
    appId: '1:720438105685:web:67357efba545f13f1a26dc',
    messagingSenderId: '720438105685',
    projectId: 'smart-ats-qr-code',
    authDomain: 'smart-ats-qr-code.firebaseapp.com',
    storageBucket: 'smart-ats-qr-code.firebasestorage.app',
  );
}
await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
